const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const exportsList='state,LINES,KEYS,TYPE_INFO,unit,stageData,countTypes,activeCounts,synergyTier,synergyBonuses,makeCombatant,applyBonus,damage,normalAttack,cast,heal,applyDot,processEffects,moveToward,startBattle,combatTick,finishBattle,summonZapdos,tryMerge,buy,returnToBench,placeSelected,sellSelected,buyXP,rollShop,reset,render,ITEM_DEFS,COMPONENTS,ITEM_RECIPES,newItem,itemBonuses,locateItem,selectItem,combinationPlan,confirmCombine,cancelCombine,equipSelectedItem,removeItem,prepareItemRewards,chooseItemReward';
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\}\)\(\);\s*$/,`globalThis.game={${exportsList}};})();`);
function setup(){
  const nodes=new Map(),listeners={};
  function element(){
    const e={children:[],style:{},dataset:{},className:'',textContent:'',classList:{add(){},remove(){}},
      appendChild(c){this.children.push(c);if(c.id)nodes.set('#'+c.id,c)},prepend(c){this.children.unshift(c)},
      querySelector(){return element()},querySelectorAll(selector){return this.children.filter(c=>c.className.split(' ').includes(selector.slice(1)))}};
    let content='';Object.defineProperty(e,'innerHTML',{get:()=>content,set:v=>{content=v;e.children=[]}});return e;
  }
  let seed=123456;
  const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
  const context={Math:math,document:{querySelector:s=>{if(!nodes.has(s))nodes.set(s,element());return nodes.get(s)},createElement:element,addEventListener:(name,cb)=>listeners[name]=cb},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){}};
  vm.createContext(context);vm.runInContext(script,context);
  const g=context.game;
  function fighter(line,side='player',stage=0){const c=g.makeCombatant(g.unit(line,stage),side,side==='player'?0:1,side==='player'?3:2);g.applyBonus(c,{});return c}
  function field(keys){g.state.board.fill(null);keys.forEach((k,i)=>g.state.board[21+i]=g.unit(k));g.state.level=Math.max(2,keys.length)}
  return {g,s:g.state,nodes,math,fighter,field};
}
const sets={Fire:['charmander','vulpix','ponyta','growlithe','cyndaquil'],Water:['squirtle','psyduck','chinchou','slowpoke','wooper'],Electric:['pikachu','magnemite','voltorb','mareep','chinchou'],Grass:['bulbasaur','oddish','paras','exeggcute','hoppip'],Psychic:['abra','exeggcute','slowpoke','drowzee','natu'],Flying:['pidgey','zubat','spearow','natu','hoppip'],Poison:['bulbasaur','weedle','nidoranf','zubat','oddish'],Ground:['sandshrew','diglett','wooper','geodude','phanpy']};

test('33 base lines, valid evolution data, no legendaries in shop',()=>{const {g}=setup();assert.equal(g.KEYS.length,33);const dex=new Set();for(const l of Object.values(g.LINES)){assert([1,2,3].includes(l.cost));assert.equal(l.types.length,l.stages.length);for(const [name,id] of l.stages){assert(name);assert(id>=1&&id<=251);assert(![144,145,146,150,151,243,244,245,249,250,251].includes(id));assert(!dex.has(id));dex.add(id)}}});
for(const [type,keys] of Object.entries(sets))test(`${type}: thresholds 3/5 reachable with base units; bench excluded`,()=>{const {g,s,field}=setup();for(let n=0;n<=5;n++){field(keys.slice(0,n));s.bench=keys.slice(n).map(k=>g.unit(k));assert.equal(g.activeCounts()[type],n);assert.equal(g.synergyTier(type,n),n>=5?2:n>=3?1:0)}});
test('duplicates, evolutionary stages and summons do not inflate counts',()=>{const {g,fighter}=setup();const units=[fighter('pikachu'),fighter('pikachu','player',1),fighter('chinchou')];const summon={line:'zapdos',types:['Electric','Flying'],summoned:true};let counts=g.countTypes([...units,summon]);assert.equal(counts.Electric,2);assert.equal(counts.Water,1);assert.equal(counts.Flying,0)});
test('evolution changes types correctly; Beedrill is not Flying',()=>{const {g,fighter}=setup();assert.equal(g.countTypes([fighter('charmander'),fighter('charmander','player',2)]).Flying,1);assert.equal(g.countTypes([fighter('weedle','player',2)]).Flying,0)});
test('bonuses affect only matching types and tier 5 replaces tier 3',()=>{const {g}=setup();const water=g.makeCombatant(g.unit('squirtle'),'player',0,3);const fire=g.makeCombatant(g.unit('charmander'),'player',1,3);g.applyBonus(water,{Water:2,Fire:2,Ground:2});g.applyBonus(fire,{Water:2,Fire:2});assert.equal(water.maxHp,Math.round(118*1.35));assert.equal(water.atk,15);assert.equal(water.def,11);assert.equal(fire.maxHp,82);assert.equal(fire.atk,Math.round(22*1.30))});
test('all attribute bonuses match approved values',()=>{const {g}=setup();const data=[['Fire','charmander','atk',22,[1.15,1.30]],['Water','squirtle','maxHp',118,[1.20,1.35]],['Ground','sandshrew','def',12,[1.20,1.40]]];for(const [type,key,prop,base,factors] of data)for(let tier=1;tier<=2;tier++){const c=g.makeCombatant(g.unit(key),'player',0,3);g.applyBonus(c,{[type]:tier});assert.equal(c[prop],Math.round(base*factors[tier-1]))}for(let tier=1;tier<=2;tier++){const c=g.makeCombatant(g.unit('pikachu'),'player',0,3);g.applyBonus(c,{Electric:tier});assert.equal(c.speed,118*1.2)}const psychic=g.makeCombatant(g.unit('abra'),'player',0,3);g.applyBonus(psychic,{Psychic:1});assert.equal(psychic.mana,25);const psychic5=g.makeCombatant(g.unit('abra'),'player',0,3);g.applyBonus(psychic5,{Psychic:2});assert.equal(psychic5.mana,40);assert.equal(psychic5.bonus.power,1.2);const flying=g.makeCombatant(g.unit('pidgey'),'player',0,3);g.applyBonus(flying,{Flying:2});assert.equal(flying.speed,105*1.15);assert.equal(flying.bonus.dodge,.2)});
test('regen uses elapsed combat time and respects max HP',()=>{const {g,fighter}=setup();for(const [key,tiers,rate] of [['squirtle',{Water:2},.02],['bulbasaur',{Grass:1},.02],['bulbasaur',{Grass:2},.04]]){const c=fighter(key);g.applyBonus(c,tiers);c.hp=20;g.processEffects(c,2999);assert.equal(c.hp,20);g.processEffects(c,3000);assert.equal(c.hp,20+Math.round(c.maxHp*rate));g.processEffects(c,3001);assert.equal(c.hp,20+Math.round(c.maxHp*rate));c.hp=c.maxHp-1;g.processEffects(c,6000);assert.equal(c.hp,c.maxHp)}});
test('Ground shield absorbs damage before HP',()=>{const {g,fighter}=setup();const c=fighter('sandshrew');g.applyBonus(c,{Ground:2});assert.equal(c.shield,Math.round(c.maxHp*.15));const attacker=fighter('pikachu');g.damage(attacker,c,10);assert.equal(c.hp,c.maxHp);assert(c.shield<Math.round(c.maxHp*.15))});
test('Flying dodge affects basic attacks only',()=>{const {g,fighter,math}=setup();const a=fighter('pikachu'),t=fighter('pidgey');g.applyBonus(t,{Flying:2});math.random=()=>0;g.damage(a,t,20,'basic');assert.equal(t.hp,t.maxHp);g.damage(a,t,20,'ability');assert(t.hp<t.maxHp)});
test('Fire burn applies only from abilities: 6% total over 3 seconds, no stacking',()=>{const {g,fighter,s}=setup();s.combat={elapsedMs:0};const a=fighter('charmander'),t=fighter('squirtle','enemy');g.applyBonus(a,{Fire:2});t.maxHp=t.hp=1000;g.damage(a,t,1,'basic');assert.equal(t.effects.burn,undefined);g.damage(a,t,1,'ability');g.applyDot(t,'burn',.02);const hp=t.hp;g.processEffects(t,999);assert.equal(t.hp,hp);g.processEffects(t,1000);assert.equal(t.hp,hp-20);g.processEffects(t,3000);assert.equal(t.hp,hp-60);assert.equal(t.effects.burn,undefined)});
test('Poison only from basics; refresh does not delay ticks; healing reduction expires',()=>{const {g,fighter,s}=setup();s.combat={elapsedMs:0};const a=fighter('weedle'),t=fighter('squirtle','enemy');g.applyBonus(a,{Poison:2});t.maxHp=1000;t.hp=500;g.damage(a,t,1,'ability');assert.equal(t.effects.poison,undefined);g.damage(a,t,1,'basic');assert.equal(t.effects.poison.rate,.02);const before=t.hp;g.heal(t,100);assert.equal(t.hp,before+70);s.combat.elapsedMs=900;g.applyDot(t,'poison',.02,.3);assert.equal(t.effects.poison.nextAt,1000);const hp=t.hp;g.processEffects(t,1000);assert.equal(t.hp,hp-20);g.processEffects(t,3000);assert.equal(t.hp,hp-60);assert(t.effects.poison);g.processEffects(t,3900);assert.equal(t.effects.poison,undefined);const cleared=t.hp;g.heal(t,100);assert.equal(t.hp,cleared+100)});
test('Grass roots only on first cast and permits attacks while rooted',()=>{const {g,fighter,s}=setup();const a=fighter('hoppip'),t=fighter('squirtle','enemy');a.x=0;a.y=3;t.x=4;t.y=3;t.hp=t.maxHp=10000;g.applyBonus(a,{Grass:2});s.combat={units:[a,t],elapsedMs:0};g.cast(a,[t],[a]);assert.equal(t.rootUntil,1500);g.moveToward(t,a);assert.equal(t.x,4);const hp=a.hp;g.normalAttack(t,a);assert(a.hp<hp);s.combat.elapsedMs=1500;g.moveToward(t,a);assert.equal(t.x,3);g.cast(a,[t],[a]);assert.equal(t.rootUntil,1500)});
test('Psychic power improves ability damage, healing and shields',()=>{const {g,fighter}=setup();for(const kind of ['blast','heal','shield']){const c=fighter('slowpoke'),target=fighter('squirtle','enemy'),ally=fighter('pikachu');g.applyBonus(c,{Psychic:2});c.ability={kind,power:.5};ally.maxHp=1000;ally.hp=1;target.def=0;g.cast(c,[target],[c,ally]);if(kind==='blast')assert.equal(target.maxHp-target.hp,Math.round(c.atk*.5*1.2));if(kind==='heal')assert.equal(ally.hp,1+Math.round(c.maxHp*.5*1.2));if(kind==='shield')assert.equal(c.shield,Math.round(c.maxHp*.5*1.2))}});
test('no type weaknesses, resistances or immunities in damage',()=>{const {g,fighter}=setup();for(const attackType of Object.keys(sets)){let expected;for(const defenseType of [...Object.keys(sets),'Ghost','Steel','Normal','Rock']){const a=fighter('squirtle'),t=fighter('charmander','enemy');a.types=[attackType];t.types=[defenseType];g.damage(a,t,30,'ability');const lost=t.maxHp-t.hp;if(expected===undefined)expected=lost;assert.equal(lost,expected,attackType+' -> '+defenseType)}}});
test('last enemy killed before later ally acts does not throw',()=>{const {g,s,fighter}=setup();const a=fighter('abra'),b=fighter('abra'),e=fighter('abra','enemy');for(const c of [a,b,e])c.meter=100;a.atk=9999;e.hp=1;s.combat={units:[a,b,e],ticks:0,elapsedMs:0};s.battle=true;assert.doesNotThrow(()=>g.combatTick());assert(e.dead)});
test('poison or burn death prevents action and regen resurrection',()=>{for(const kind of ['poison','burn']){const {g,s,fighter}=setup();const a=fighter('bulbasaur'),e=fighter('abra','enemy');g.applyBonus(a,{Grass:2});a.hp=1;a.meter=100;a.atk=9999;g.applyDot(a,kind,.5);s.combat={units:[a,e],ticks:11,elapsedMs:2860};s.battle=true;g.combatTick();assert(a.dead);assert.equal(a.hp,0);assert.equal(e.hp,e.maxHp)}});
test('Zapdos spawns once at Electric 5 in a free allied cell and stays out of roster/counts',()=>{const {g,s,field}=setup();field(sets.Electric);g.startBattle();let summons=s.combat.units.filter(c=>c.summoned&&c.side==='player');assert.equal(summons.length,1);const z=summons[0];assert(z.y>=3);assert.equal(s.combat.units.filter(c=>c.x===z.x&&c.y===z.y).length,1);assert.equal(z.maxHp,180);assert.equal(z.speed,105);assert.equal(g.activeCounts().Electric,5);assert.equal(s.board.filter(Boolean).length,5);assert.equal(s.bench.filter(Boolean).length,0);g.summonZapdos('player');assert.equal(s.combat.units.filter(c=>c.summoned&&c.side==='player').length,1);g.finishBattle(true);assert.equal(s.combat,null);assert(!s.board.some(c=>c&&c.line==='zapdos'));g.startBattle();assert.equal(s.combat.units.filter(c=>c.summoned&&c.side==='player').length,1)});
test('Electric 4 and duplicate Electric units cannot summon Zapdos',()=>{const {g,s,field}=setup();field([...sets.Electric.slice(0,4),'pikachu']);g.startBattle();assert.equal(s.combat.units.filter(c=>c.side==='player'&&c.summoned).length,0)});
test('enemy summon is temporary and does not add trainer damage',()=>{const {g,s,fighter}=setup();const e=fighter('pikachu','enemy');s.combat={units:[e],ticks:0,elapsedMs:0};g.summonZapdos('enemy');assert.equal(s.combat.units.length,2);assert(s.combat.units[1].y<3);g.finishBattle(false);assert.equal(s.hp,93)});
test('all 33 lines merge through each stage and final forms do not merge',()=>{const {g,s}=setup();for(const key of g.KEYS){for(let stage=0;stage<g.LINES[key].stages.length;stage++){s.board.fill(null);s.bench.fill(null);for(let i=0;i<3;i++)s.bench[i]=g.unit(key,stage);g.tryMerge(key,stage);const final=stage===g.LINES[key].stages.length-1;const units=s.bench.filter(Boolean);assert.equal(units.length,final?3:1);assert.equal(units[0].stage,final?stage:stage+1)}}});
test('buying ninth base copy cascades to final evolution and preserves field location',()=>{const {g,s}=setup();s.gold=100;s.board[21]=g.unit('mareep',1);s.bench[0]=g.unit('mareep',1);s.bench[1]=g.unit('mareep');s.bench[2]=g.unit('mareep');s.shop=['mareep'];g.buy(0);assert.equal(s.board[21].stage,2);assert.equal(s.bench.filter(Boolean).length,0);assert.equal(s.gold,98)});
test('bench click return, field limit, sale and XP preserved',()=>{const {g,s,nodes}=setup();s.bench[0]=g.unit('pikachu');g.render();nodes.get('#bench').children[0].children[0].onclick({stopPropagation(){}});nodes.get('#board').children[21].onclick();assert(s.board[21]);nodes.get('#bench').children[2].onclick();assert(s.bench[2]);assert.equal(s.board[21],null);s.board[21]=g.unit('abra');s.board[22]=g.unit('abra');g.placeSelected(23);assert.equal(s.board[23],null);s.bench[3]=g.unit('mareep',1);s.selected={id:s.bench[3].id};s.gold=0;g.sellSelected();assert.equal(s.gold,6);s.gold=8;g.buyXP();g.buyXP();assert.equal(s.level,3);assert.equal(s.gold,0)});
test('win/loss streak income, interest and restart preserved',()=>{const {g,s}=setup();for(const win of [true,false]){s.hp=100;s.round=1;for(let i=1;i<=7;i++){s.gold=20;s.combat={units:[]};g.finishBattle(win);assert.equal(s.streak,i);assert.equal(s.gold,20+(win?6:5)+2+Math.min(3,Math.max(0,i-2)))}}g.reset();assert.equal(s.streak,0);assert.equal(s.streakResult,null)});
test('full combats for each composition at all 15 rounds terminate with valid state',()=>{for(const keys of Object.values(sets)){for(let round=1;round<=15;round++){const {g,s,field}=setup();field(keys);s.round=round;s.board.forEach(u=>{if(u)u.stage=1});g.startBattle();let ticks=0;while(s.battle&&ticks++<430){g.combatTick();if(s.combat)for(const c of s.combat.units){assert(Number.isFinite(c.hp));assert(Number.isFinite(c.speed));assert(c.hp>=0&&c.hp<=c.maxHp);assert(c.x>=0&&c.x<7&&c.y>=0&&c.y<6)}}assert(!s.battle);assert.equal(s.combat,null);assert(Number.isFinite(s.gold));assert(s.round===round+1||s.gameOver)}}});

test('items: all 15 unordered pairs preview and combine only after confirmation',()=>{const {g,s}=setup();assert.equal(g.COMPONENTS.length,5);assert.equal(Object.keys(g.ITEM_RECIPES).length,15);for(let i=0;i<5;i++)for(let j=i;j<5;j++){s.inventory=[g.newItem(g.COMPONENTS[i]),g.newItem(g.COMPONENTS[j])];const ids=s.inventory.map(x=>x.id);g.selectItem(ids[0]);g.selectItem(ids[1]);const plan=g.combinationPlan();assert(plan);assert.equal(s.inventory.length,2);assert.equal(plan.target,null);g.confirmCombine();assert.equal(s.inventory.length,1);assert.equal(s.inventory[0].key,plan.key);assert.equal(s.pendingCombine,null);g.confirmCombine();assert.equal(s.inventory.length,1)}});
test('items: cancel is lossless; mixed locations combine into holder, duplicate result goes to bag',()=>{const {g,s}=setup();const u=g.unit('pikachu');s.bench[0]=u;u.items=[g.newItem('claw')];s.inventory=[g.newItem('claw')];g.selectItem(u.items[0].id);g.selectItem(s.inventory[0].id);g.cancelCombine();assert.equal(u.items.length,1);assert.equal(s.inventory.length,1);g.selectItem(u.items[0].id);g.selectItem(s.inventory[0].id);g.confirmCombine();assert.equal(u.items[0].key,'muscle');assert.equal(s.inventory.length,0);u.items.push(g.newItem('claw'));s.inventory.push(g.newItem('claw'));g.selectItem(u.items[1].id);g.selectItem(s.inventory[0].id);assert.equal(g.combinationPlan().target,null);g.confirmCombine();assert.equal(u.items.length,1);assert.equal(s.inventory[0].key,'muscle')});
test('items: three slots, duplicate equipment blocked, removal free',()=>{const {g,s}=setup();const u=g.unit('pikachu');s.bench[0]=u;s.selected={id:u.id};s.inventory=['muscle','muscle','feather','crystal','seed'].map(g.newItem);const gold=s.gold;let ids=s.inventory.map(i=>i.id);for(const id of ids){s.selectedItem=id;g.equipSelectedItem()}assert.equal(u.items.length,3);assert.equal(u.items.filter(i=>i.key==='muscle').length,1);assert.equal(s.inventory.length,2);const item=u.items[0];g.removeItem(item.id);assert.equal(u.items.length,2);assert(s.inventory.includes(item));assert.equal(s.gold,gold)});
test('items: actions forbidden during combat/game-over; stale confirmations cannot duplicate',()=>{const {g,s}=setup();const u=g.unit('pikachu');s.bench[0]=u;s.selected={id:u.id};s.inventory=[g.newItem('claw'),g.newItem('claw')];g.selectItem(s.inventory[0].id);g.selectItem(s.inventory[1].id);for(const mode of ['battle','gameOver']){s[mode]=true;g.confirmCombine();g.equipSelectedItem();assert.equal(s.inventory.length,2);assert.equal(u.items.length,0);s[mode]=false}s.inventory.pop();g.confirmCombine();assert.equal(s.inventory.length,1)});
test('items: evolution conserves nine items and returns duplicates/excess without auto-combining',()=>{const {g,s}=setup();s.inventory=[];const trio=[g.unit('mareep'),g.unit('mareep'),g.unit('mareep')];trio[0].items=['muscle','claw','seed'].map(g.newItem);trio[1].items=['muscle','scarf','feather'].map(g.newItem);trio[2].items=['bell','seed','shell'].map(g.newItem);const ids=trio.flatMap(u=>u.items.map(i=>i.id)).sort();s.board[21]=trio[0];s.bench[0]=trio[1];s.bench[1]=trio[2];g.tryMerge('mareep',0);const evolved=s.board[21];assert.equal(evolved.stage,1);assert.equal(evolved.items.length,3);assert.equal(new Set(evolved.items.map(i=>i.key)).size,3);assert.equal(s.inventory.length,6);assert.deepEqual([...evolved.items,...s.inventory].map(i=>i.id).sort(),ids)});
test('items: cascade evolution and sale return every item, without gold value from items',()=>{const {g,s}=setup();s.inventory=[];s.gold=100;const a=g.unit('mareep',1),b=g.unit('mareep',1),c=g.unit('mareep'),d=g.unit('mareep');a.items=[g.newItem('muscle')];b.items=[g.newItem('muscle'),g.newItem('bell')];c.items=[g.newItem('seed')];d.items=[g.newItem('shell')];const ids=[a,b,c,d].flatMap(u=>u.items.map(i=>i.id)).sort();s.board[21]=a;s.bench[0]=b;s.bench[1]=c;s.bench[2]=d;s.shop=['mareep'];g.buy(0);assert.equal(s.board[21].stage,2);s.selected={id:s.board[21].id};g.sellSelected();assert.deepEqual(Array.from(s.inventory,i=>i.id).sort(),ids);assert.equal(s.gold,116);assert.equal(s.board[21],null)});
test('items: preparation click flow selects, equips, previews, confirms and removes',()=>{const {g,s,nodes}=setup();const u=g.unit('pikachu');s.bench[0]=u;s.selected={id:u.id};s.inventory=[g.newItem('claw'),g.newItem('claw')];g.render();nodes.get('#itemInventory').children[0].onclick();nodes.get('#equipItemBtn').onclick();assert.equal(u.items.length,1);nodes.get('#equipmentSlots').children[0].children[0].onclick();nodes.get('#itemInventory').children[0].onclick();const preview=nodes.get('#itemPreview').children[0];assert(preview.innerHTML.includes('Faixa Muscular'));preview.children[0].onclick();assert.equal(u.items[0].key,'muscle');nodes.get('#equipmentSlots').children[0].children[1].onclick();assert.equal(u.items.length,0);assert.equal(s.inventory[0].key,'muscle')});
test('items: rewards total ten components, once each, three distinct package options',()=>{const {g,s}=setup();assert.equal(s.inventory.length,2);for(let r=1;r<=15;r++){s.round=r;g.prepareItemRewards();g.prepareItemRewards();if([4,7,10,13].includes(r)){assert.equal(s.rewardChoices.options.length,3);assert.equal(new Set(s.rewardChoices.options.map(p=>Array.from(p).sort().join('+'))).size,3);const len=s.inventory.length;g.chooseItemReward(1);g.chooseItemReward(1);g.prepareItemRewards();assert.equal(s.inventory.length,len+2);assert.equal(s.rewardChoices,null)}else assert.equal(s.rewardChoices,null)}assert.equal(s.inventory.length,10);assert.equal(s.rewardRounds.length,5);assert.equal(s.gold,10)});
test('items: victory and defeat both offer round-four reward; choice gates battle',()=>{for(const win of [true,false]){const {g,s,field}=setup();field(['pikachu']);s.round=3;s.combat={units:[]};g.finishBattle(win);assert.equal(s.round,4);assert(s.rewardChoices);g.startBattle();assert.equal(s.battle,false);g.chooseItemReward(0);g.startBattle();assert.equal(s.battle,true)}});
test('items: reset clears equipment, selections and old rewards and grants only starting pair',()=>{const {g,s}=setup();const u=g.unit('pikachu');u.items=[g.newItem('muscle')];s.bench[0]=u;s.round=4;g.prepareItemRewards();s.selectedItem=s.inventory[0].id;g.reset();assert.equal(s.inventory.length,2);assert.equal(s.bench.filter(Boolean).length,0);assert.equal(s.selectedItem,null);assert.equal(s.pendingCombine,null);assert.equal(s.rewardChoices,null);assert.equal(s.rewardRounds.length,1)});
function equipped({g},line,keys,tiers={}){const u=g.unit(line);u.items=keys.map(g.newItem);const c=g.makeCombatant(u,'player',0,3);g.applyBonus(c,tiers);return c}
test('items: exact stat totals replace components and stack additively across items, with traits afterward',()=>{const ctx=setup(),{g}=ctx;for(const [key,stat,factor] of [['muscle','atk',1.25],['scarf','speed',1.25],['glasses','power',1.25],['metal','def',1.35],['vest','maxHp',1.25]]){const c=equipped(ctx,'squirtle',[key]);const base=g.stageData(g.unit('squirtle'));if(stat==='power')assert.equal(c.bonus.power,factor);else if(stat==='speed')assert.equal(c.speed,base.speed*factor);else assert.equal(c[stat],Math.round((stat==='maxHp'?base.hp:base[stat])*factor))}const c=equipped(ctx,'charmander',['muscle','orb'],{Fire:2});assert.equal(c.atk,Math.round(22*1.45*1.3));assert.equal(c.bonus.power,1.2);const holder=equipped(ctx,'squirtle',['vest','barrier'],{Water:2});assert.equal(holder.maxHp,Math.round(118*1.25*1.35));assert.equal(holder.shield,Math.round(holder.maxHp*.2));const psychic=equipped(ctx,'abra',['glasses'],{Psychic:2});assert.equal(psychic.bonus.power,1.5)});
test('items: mana per attack caps at 100; Restos regen stacks with Water and respects poison healing reduction',()=>{const ctx=setup(),{g,fighter}=ctx;const a=equipped(ctx,'pikachu',['amulet']),t=fighter('squirtle','enemy');t.hp=t.maxHp=1000;g.normalAttack(a,t);assert.equal(a.mana,44);a.mana=95;g.normalAttack(a,t);assert.equal(a.mana,100);const tank=equipped(ctx,'squirtle',['leftovers'],{Water:2});tank.hp=10;g.processEffects(tank,2999);assert.equal(tank.hp,10);g.processEffects(tank,3000);assert.equal(tank.hp,10+Math.round(tank.maxHp*.04));g.applyDot(tank,'poison',0,.3);const before=tank.hp;g.heal(tank,100);assert.equal(tank.hp,before+70)});
test('items: leech excludes shields, overkill, periodic damage and the other attack category',()=>{const ctx=setup(),{g,fighter}=ctx;const a=equipped(ctx,'charmander',['fang']),t=fighter('squirtle','enemy');a.hp=10;t.def=0;t.maxHp=t.hp=1000;t.shield=80;g.damage(a,t,100,'basic');assert.equal(a.hp,13);t.shield=100;g.damage(a,t,50,'basic');assert.equal(a.hp,13);t.shield=0;g.damage(a,t,100,'ability');assert.equal(a.hp,13);g.applyDot(t,'burn',.02);g.processEffects(t,3000);assert.equal(a.hp,13);t.hp=10;g.damage(a,t,100,'basic');assert.equal(a.hp,15);const caster=equipped(ctx,'abra',['bell']),e=fighter('squirtle','enemy');caster.hp=10;e.def=0;e.hp=e.maxHp=1000;g.damage(caster,e,100,'basic');assert.equal(caster.hp,10);g.damage(caster,e,100,'ability');assert.equal(caster.hp,25);caster.effects.poison={antiHeal:.3};g.damage(caster,e,100,'ability');assert.equal(caster.hp,36)});
test('items: ability power applies to damage, cure and shield, not just attacks',()=>{const ctx=setup(),{g,fighter}=ctx;for(const kind of ['blast','heal','shield']){const c=equipped(ctx,'squirtle',['glasses']),t=fighter('pikachu','enemy'),ally=fighter('pikachu');t.def=0;t.hp=t.maxHp=1000;ally.hp=1;ally.maxHp=1000;c.ability={kind,power:.5};g.cast(c,[t],[c,ally]);if(kind==='blast')assert.equal(1000-t.hp,Math.round(c.atk*.5*1.25));if(kind==='heal')assert.equal(ally.hp,1+Math.round(c.maxHp*.5*1.25));if(kind==='shield')assert.equal(c.shield,Math.round(c.maxHp*.5*1.25))}});
test('items: battle copies do not mutate original stats or inventory; Zapdos cannot receive items',()=>{const {g,s,field}=setup();field(sets.Electric);s.board[21].items=[g.newItem('vest'),g.newItem('muscle')];const owned=JSON.stringify(s.board);g.startBattle();const first=s.combat.units.find(c=>c.side==='player'&&!c.summoned),hp=first.maxHp;const z=s.combat.units.find(c=>c.summoned&&c.side==='player');assert.equal(z.maxHp,180);const item=g.newItem('vest');s.inventory.push(item);s.selected={id:z.cid};s.selectedItem=item.id;g.equipSelectedItem();assert(s.inventory.includes(item));g.finishBattle(true);assert.equal(JSON.stringify(s.board),owned);g.startBattle();assert.equal(s.combat.units.find(c=>c.side==='player'&&!c.summoned).maxHp,hp)});
test('items: entire 15-round journey with rewards and equipped combat terminates without losing equipment',()=>{const {g,s,field}=setup();field(sets.Water);s.hp=10000;s.board[21].items=['leftovers','vest','barrier'].map(g.newItem);s.board[22].items=['orb','bell','amulet'].map(g.newItem);const before=JSON.stringify(s.board);for(let round=1;round<=15;round++){if(s.rewardChoices)g.chooseItemReward(0);assert.equal(s.round,round);g.startBattle();let ticks=0;while(s.battle&&ticks++<430)g.combatTick();assert.equal(s.battle,false);assert.equal(JSON.stringify(s.board),before)}assert(s.gameOver);assert.equal(s.inventory.length,10);assert.equal(s.rewardRounds.length,5)});
