const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const exportsList='state,LINES,KEYS,TYPE_INFO,unit,stageData,countTypes,activeCounts,synergyTier,synergyBonuses,makeCombatant,applyBonus,damage,normalAttack,cast,heal,applyDot,processEffects,moveToward,startBattle,combatTick,finishBattle,summonZapdos,tryMerge,buy,returnToBench,placeSelected,sellSelected,buyXP,rollShop,reset,render,ITEM_DEFS,COMPONENTS,ITEM_RECIPES,newItem,itemBonuses,locateItem,selectItem,combinationPlan,confirmCombine,cancelCombine,equipSelectedItem,removeItem,prepareItemRewards,chooseItemReward,BOSS_DEFS,BOSS_ROUNDS,ENEMY_TRAIT_POOLS,bossKeyForRound,difficultyProfile,generateEnemy,makeBossCombatant,generateBossEnemy,grantBossReward,randomLegendaryBoss,ENEMY_KEYS,SPECIAL_KEYS,unitPrice,shopOdds,stageOdds,weightedCost,rollStage,normalizeOffer,applySpecialBattleStart,applyStun,applyRoot,takeDamage,typeCatalog,openTypeInfo,closeTypeInfo,renderSynergies,rarityName,abilityDescription,passiveDescription,renderBattlePreview,renderBattleSummary,renderShopInfo,openShopInfo,closeShopInfo,toggleShopLock,showFinalSummary,closeFinalSummary,openRules,closeRules,openBackpack,closeBackpack,openHistory,closeHistory,startGame';
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/\}\)\(\);\s*$/,`globalThis.game={${exportsList}};})();`);
function setup(){
  const nodes=new Map(),listeners={};
  function element(){
    const classes=new Set();const e={children:[],style:{},dataset:{},className:'',textContent:'',classList:{add(...xs){xs.forEach(x=>classes.add(x))},remove(...xs){xs.forEach(x=>classes.delete(x))},toggle(x,v){if(v===undefined){if(classes.has(x)){classes.delete(x);return false}classes.add(x);return true}if(v)classes.add(x);else classes.delete(x);return !!v},contains(x){return classes.has(x)}},
      setAttribute(k,v){this[k]=String(v)},appendChild(c){this.children.push(c);if(c.id)nodes.set('#'+c.id,c)},prepend(c){this.children.unshift(c)},
      querySelector(){return element()},querySelectorAll(selector){return this.children.filter(c=>c.className.split(' ').includes(selector.slice(1)))}};
    let content='';Object.defineProperty(e,'innerHTML',{get:()=>content,set:v=>{content=v;e.children=[]}});return e;
  }
  let seed=123456;
  const math=Object.create(Math);math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
  const context={Math:math,document:{querySelector:s=>{if(!nodes.has(s))nodes.set(s,element());return nodes.get(s)},createElement:element,addEventListener:(name,cb)=>listeners[name]=cb},setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){}};
  vm.createContext(context);vm.runInContext(script,context);
  const g=context.game;
  function fighter(line,side='player',stage=0){const c=g.makeCombatant(g.unit(line,stage),side,side==='player'?0:1,side==='player'?3:2);g.applyBonus(c,{});return c}
  function field(keys){g.state.board.fill(null);keys.forEach((entry,i)=>{const [k,stage]=Array.isArray(entry)?entry:[entry,0];g.state.board[21+i]=g.unit(k,stage)});g.state.level=Math.max(2,keys.length)}
  return {g,s:g.state,nodes,math,fighter,field};
}
const sets={Fire:['charmander','magby','torchic','litwick','cyndaquil'],Water:['squirtle','horsea','spheal','mudkip','lotad'],Electric:['pichu','magnemite','shinx','mareep','tynamo'],Grass:['bulbasaur','oddish','bellsprout','hoppip','lotad'],Psychic:['abra','ralts','solosis','hatenna','gothita'],Flying:['pidgey','zubat','hoppip',['caterpie',2],['charmander',2]],Poison:['bulbasaur','weedle','nidoranf','zubat','oddish'],Ground:['rhyhorn','trapinch','geodude',['mudkip',1],['nidoranf',2]],Dragon:['dratini','gible',['trapinch',1],['horsea',2]]};

test('v0.7 roster keeps 33 standard lines and exactly five special 4-star lines, all with three stages',()=>{const {g}=setup();assert.equal(g.KEYS.length,38);assert.equal(g.ENEMY_KEYS.length,33);assert.equal(g.SPECIAL_KEYS.length,5);assert.deepEqual(Array.from(g.SPECIAL_KEYS).sort(),['beldum','dratini','gastly','gible','larvitar']);const dex=new Set();for(const [key,l] of Object.entries(g.LINES)){assert([1,2,3,4].includes(l.cost));assert.equal(l.stages.length,3,key+' must have exactly three stages');assert.equal(l.types.length,3);if(l.special)assert.equal(l.cost,4);else assert([1,2,3].includes(l.cost));for(const [name,id] of l.stages){assert(name);assert(id>=1&&id<=1025);assert(![144,145,146,150,151,243,244,245,249,250,251].includes(id));assert(!dex.has(id));dex.add(id)}}});

for(const [type,keys] of Object.entries(sets))test(`${type}: configured thresholds reachable with valid forms; bench excluded`,()=>{const {g,s,field}=setup();const levels=Array.from(g.TYPE_INFO[type].levels);for(let n=0;n<=keys.length;n++){field(keys.slice(0,n));s.bench=keys.slice(n).map(entry=>{const [k,stage]=Array.isArray(entry)?entry:[entry,0];return g.unit(k,stage)});assert.equal(g.activeCounts()[type],n);assert.equal(g.synergyTier(type,n),n>=levels[1]?2:n>=levels[0]?1:0)}});

test('duplicates, evolutionary stages and summons do not inflate counts',()=>{const {g,fighter}=setup();const units=[fighter('pichu'),fighter('pichu','player',1),fighter('tynamo'),fighter('mudkip')];const summon={line:'zapdos',types:['Electric','Flying'],summoned:true};let counts=g.countTypes([...units,summon]);assert.equal(counts.Electric,2);assert.equal(counts.Water,1);assert.equal(counts.Flying,0);assert.equal(counts.Dragon,0)});
test('evolution changes types correctly; Beedrill is not Flying',()=>{const {g,fighter}=setup();assert.equal(g.countTypes([fighter('charmander'),fighter('charmander','player',2)]).Flying,1);assert.equal(g.countTypes([fighter('weedle','player',2)]).Flying,0)});
test('bonuses affect only matching types and tier 5 replaces tier 3',()=>{const {g}=setup();const water=g.makeCombatant(g.unit('squirtle'),'player',0,3);const fire=g.makeCombatant(g.unit('charmander'),'player',1,3);g.applyBonus(water,{Water:2,Fire:2,Ground:2});g.applyBonus(fire,{Water:2,Fire:2});assert.equal(water.maxHp,Math.round(118*1.35));assert.equal(water.atk,15);assert.equal(water.def,11);assert.equal(fire.maxHp,82);assert.equal(fire.atk,Math.round(22*1.30))});
test('all attribute bonuses match approved values',()=>{const {g}=setup();const data=[['Fire','charmander','atk',22,[1.15,1.30]],['Water','squirtle','maxHp',118,[1.20,1.35]],['Ground','rhyhorn','def',12,[1.20,1.40]]];for(const [type,key,prop,base,factors] of data)for(let tier=1;tier<=2;tier++){const c=g.makeCombatant(g.unit(key),'player',0,3);g.applyBonus(c,{[type]:tier});assert.equal(c[prop],Math.round(base*factors[tier-1]))}for(let tier=1;tier<=2;tier++){const c=g.makeCombatant(g.unit('pichu'),'player',0,3);g.applyBonus(c,{Electric:tier});assert.equal(c.speed,118*1.2)}const psychic=g.makeCombatant(g.unit('abra'),'player',0,3);g.applyBonus(psychic,{Psychic:1});assert.equal(psychic.mana,25);const psychic5=g.makeCombatant(g.unit('abra'),'player',0,3);g.applyBonus(psychic5,{Psychic:2});assert.equal(psychic5.mana,40);assert.equal(psychic5.bonus.power,1.2);const flying=g.makeCombatant(g.unit('pidgey'),'player',0,3);g.applyBonus(flying,{Flying:2});assert.equal(flying.speed,105*1.15);assert.equal(flying.bonus.dodge,.2)});
test('Dragon 1 grants only +15 percent HP and ATK to Dragon units',()=>{const {g}=setup();const d=g.makeCombatant(g.unit('dratini'),'player',0,3),non=g.makeCombatant(g.unit('pichu'),'player',1,3);g.applyBonus(d,{Dragon:1});g.applyBonus(non,{Dragon:1});assert.equal(d.maxHp,Math.round(88*1.15));assert.equal(d.atk,Math.round(25*1.15));assert.equal(d.mana,0);assert.equal(d.dragonDamageReduction,0);assert.equal(non.maxHp,74);assert.equal(non.atk,23)});
test('Dragon 4 replaces Dragon 1 with Ascension stats, damage reduction and resurgence',()=>{const {g,s}=setup();const d=g.makeCombatant(g.unit('dratini'),'player',0,3);g.applyBonus(d,{Dragon:2});assert.equal(d.maxHp,Math.round(88*1.45));assert.equal(d.atk,Math.round(25*1.45));assert.equal(d.mana,40);assert.equal(d.dragonDamageReduction,.25);assert.equal(d.dragonAscension,true);s.combat={units:[d],elapsedMs:0};d.def=0;const hp=d.hp;assert.equal(g.takeDamage(d,40),30);assert.equal(hp-d.hp,30);d.hp=Math.round(d.maxHp*.50);const before=d.hp;const dealt=g.takeDamage(d,20);assert.equal(dealt,15);assert.equal(d.dragonResurgenceUsed,true);assert.equal(d.hp,Math.min(d.maxHp,before-15+Math.round(d.maxHp*.25)));assert.equal(d.speedBoost,.30);assert.equal(d.speedBoostUntil,4000);const after=d.hp;g.takeDamage(d,4);assert(d.hp<after);assert.equal(d.dragonResurgenceUsed,true)});
test('regen uses elapsed combat time and respects max HP',()=>{const {g,fighter}=setup();for(const [key,tiers,rate] of [['squirtle',{Water:2},.02],['bulbasaur',{Grass:1},.02],['bulbasaur',{Grass:2},.04]]){const c=fighter(key);g.applyBonus(c,tiers);c.hp=20;g.processEffects(c,2999);assert.equal(c.hp,20);g.processEffects(c,3000);assert.equal(c.hp,20+Math.round(c.maxHp*rate));g.processEffects(c,3001);assert.equal(c.hp,20+Math.round(c.maxHp*rate));c.hp=c.maxHp-1;g.processEffects(c,6000);assert.equal(c.hp,c.maxHp)}});
test('Ground shield absorbs damage before HP',()=>{const {g,fighter}=setup();const c=fighter('rhyhorn');g.applyBonus(c,{Ground:2});assert.equal(c.shield,Math.round(c.maxHp*.15));const attacker=fighter('pichu');g.damage(attacker,c,10);assert.equal(c.hp,c.maxHp);assert(c.shield<Math.round(c.maxHp*.15))});
test('Flying dodge affects basic attacks only',()=>{const {g,fighter,math}=setup();const a=fighter('pichu'),t=fighter('pidgey');g.applyBonus(t,{Flying:2});math.random=()=>0;g.damage(a,t,20,'basic');assert.equal(t.hp,t.maxHp);g.damage(a,t,20,'ability');assert(t.hp<t.maxHp)});
test('Fire burn applies only from abilities: 6% total over 3 seconds, no stacking',()=>{const {g,fighter,s}=setup();s.combat={elapsedMs:0};const a=fighter('charmander'),t=fighter('squirtle','enemy');g.applyBonus(a,{Fire:2});t.maxHp=t.hp=1000;g.damage(a,t,1,'basic');assert.equal(t.effects.burn,undefined);g.damage(a,t,1,'ability');g.applyDot(t,'burn',.02);const hp=t.hp;g.processEffects(t,999);assert.equal(t.hp,hp);g.processEffects(t,1000);assert.equal(t.hp,hp-20);g.processEffects(t,3000);assert.equal(t.hp,hp-60);assert.equal(t.effects.burn,undefined)});
test('Poison only from basics; refresh does not delay ticks; healing reduction expires',()=>{const {g,fighter,s}=setup();s.combat={elapsedMs:0};const a=fighter('weedle'),t=fighter('squirtle','enemy');g.applyBonus(a,{Poison:2});t.maxHp=1000;t.hp=500;g.damage(a,t,1,'ability');assert.equal(t.effects.poison,undefined);g.damage(a,t,1,'basic');assert.equal(t.effects.poison.rate,.02);const before=t.hp;g.heal(t,100);assert.equal(t.hp,before+70);s.combat.elapsedMs=900;g.applyDot(t,'poison',.02,.3);assert.equal(t.effects.poison.nextAt,1000);const hp=t.hp;g.processEffects(t,1000);assert.equal(t.hp,hp-20);g.processEffects(t,3000);assert.equal(t.hp,hp-60);assert(t.effects.poison);g.processEffects(t,3900);assert.equal(t.effects.poison,undefined);const cleared=t.hp;g.heal(t,100);assert.equal(t.hp,cleared+100)});
test('Grass roots only on first cast and permits attacks while rooted',()=>{const {g,fighter,s}=setup();const a=fighter('hoppip'),t=fighter('squirtle','enemy');a.x=0;a.y=3;t.x=4;t.y=3;t.hp=t.maxHp=10000;g.applyBonus(a,{Grass:2});s.combat={units:[a,t],elapsedMs:0};g.cast(a,[t],[a]);assert.equal(t.rootUntil,1500);g.moveToward(t,a);assert.equal(t.x,4);const hp=a.hp;g.normalAttack(t,a);assert(a.hp<hp);s.combat.elapsedMs=1500;g.moveToward(t,a);assert.equal(t.x,3);g.cast(a,[t],[a]);assert.equal(t.rootUntil,1500)});
test('Psychic power improves ability damage, healing and shields',()=>{const {g,fighter}=setup();for(const kind of ['blast','heal','shield']){const c=fighter('spheal'),target=fighter('squirtle','enemy'),ally=fighter('pichu');g.applyBonus(c,{Psychic:2});c.ability={kind,power:.5};ally.maxHp=1000;ally.hp=1;target.def=0;g.cast(c,[target],[c,ally]);if(kind==='blast')assert.equal(target.maxHp-target.hp,Math.round(c.atk*.5*1.2));if(kind==='heal')assert.equal(ally.hp,1+Math.round(c.maxHp*.5*1.2));if(kind==='shield')assert.equal(c.shield,Math.round(c.maxHp*.5*1.2))}});
test('no type weaknesses, resistances or immunities in damage',()=>{const {g,fighter}=setup();for(const attackType of Object.keys(sets)){let expected;for(const defenseType of [...Object.keys(sets),'Ghost','Steel','Normal','Rock']){const a=fighter('squirtle'),t=fighter('charmander','enemy');a.types=[attackType];t.types=[defenseType];g.damage(a,t,30,'ability');const lost=t.maxHp-t.hp;if(expected===undefined)expected=lost;assert.equal(lost,expected,attackType+' -> '+defenseType)}}});
test('last enemy killed before later ally acts does not throw',()=>{const {g,s,fighter}=setup();const a=fighter('abra'),b=fighter('abra'),e=fighter('abra','enemy');for(const c of [a,b,e])c.meter=100;a.atk=9999;e.hp=1;s.combat={units:[a,b,e],ticks:0,elapsedMs:0};s.battle=true;assert.doesNotThrow(()=>g.combatTick());assert(e.dead)});
test('poison or burn death prevents action and regen resurrection',()=>{for(const kind of ['poison','burn']){const {g,s,fighter}=setup();const a=fighter('bulbasaur'),e=fighter('abra','enemy');g.applyBonus(a,{Grass:2});a.hp=1;a.meter=100;a.atk=9999;g.applyDot(a,kind,.5);s.combat={units:[a,e],ticks:11,elapsedMs:2860};s.battle=true;g.combatTick();assert(a.dead);assert.equal(a.hp,0);assert.equal(e.hp,e.maxHp)}});
test('Zapdos spawns once at Electric 5 in a free allied cell and stays out of roster/counts',()=>{const {g,s,field}=setup();field(sets.Electric);g.startBattle();let summons=s.combat.units.filter(c=>c.summoned&&c.side==='player');assert.equal(summons.length,1);const z=summons[0];assert(z.y>=3);assert.equal(s.combat.units.filter(c=>c.x===z.x&&c.y===z.y).length,1);assert.equal(z.maxHp,180);assert.equal(z.speed,105);assert.equal(g.activeCounts().Electric,5);assert.equal(s.board.filter(Boolean).length,5);assert.equal(s.bench.filter(Boolean).length,0);g.summonZapdos('player');assert.equal(s.combat.units.filter(c=>c.summoned&&c.side==='player').length,1);g.finishBattle(true);assert.equal(s.combat,null);assert(!s.board.some(c=>c&&c.line==='zapdos'));g.startBattle();assert.equal(s.combat.units.filter(c=>c.summoned&&c.side==='player').length,1)});
test('Electric 4 and duplicate Electric units cannot summon Zapdos',()=>{const {g,s,field}=setup();field([...sets.Electric.slice(0,4),'pichu']);g.startBattle();assert.equal(s.combat.units.filter(c=>c.side==='player'&&c.summoned).length,0)});
test('enemy summon is temporary and does not add trainer damage',()=>{const {g,s,fighter}=setup();const e=fighter('pichu','enemy');s.combat={units:[e],ticks:0,elapsedMs:0};g.summonZapdos('enemy');assert.equal(s.combat.units.length,2);assert(s.combat.units[1].y<3);g.finishBattle(false);assert.equal(s.hp,93)});
test('all purchasable lines merge through each stage and final forms do not merge',()=>{const {g,s}=setup();for(const key of g.KEYS){for(let stage=0;stage<g.LINES[key].stages.length;stage++){s.board.fill(null);s.bench.fill(null);for(let i=0;i<3;i++)s.bench[i]=g.unit(key,stage);g.tryMerge(key,stage);const final=stage===g.LINES[key].stages.length-1;const units=s.bench.filter(Boolean);assert.equal(units.length,final?3:1);assert.equal(units[0].stage,final?stage:stage+1)}}});
test('buying ninth base copy cascades to final evolution and preserves field location',()=>{const {g,s}=setup();s.gold=100;s.board[21]=g.unit('mareep',1);s.bench[0]=g.unit('mareep',1);s.bench[1]=g.unit('mareep');s.bench[2]=g.unit('mareep');s.shop=['mareep'];g.buy(0);assert.equal(s.board[21].stage,2);assert.equal(s.bench.filter(Boolean).length,0);assert.equal(s.gold,98)});
test('bench click return, field limit, sale and XP preserved',()=>{const {g,s,nodes}=setup();s.bench[0]=g.unit('pichu');g.render();nodes.get('#bench').children[0].children[0].onclick({stopPropagation(){}});nodes.get('#board').children[21].onclick();assert(s.board[21]);nodes.get('#bench').children[2].onclick();assert(s.bench[2]);assert.equal(s.board[21],null);s.board[21]=g.unit('abra');s.board[22]=g.unit('abra');g.placeSelected(23);assert.equal(s.board[23],null);s.bench[3]=g.unit('mareep',1);s.selected={id:s.bench[3].id};s.gold=0;g.sellSelected();assert.equal(s.gold,6);s.gold=8;g.buyXP();g.buyXP();assert.equal(s.level,3);assert.equal(s.gold,0)});
test('win/loss streak income, interest and restart preserved',()=>{const {g,s}=setup();for(const win of [true,false]){s.hp=100;s.round=1;for(let i=1;i<=7;i++){s.gold=20;s.combat={units:[]};g.finishBattle(win);assert.equal(s.streak,i);assert.equal(s.gold,20+(win?6:5)+2+Math.min(3,Math.max(0,i-2)))}}g.reset();assert.equal(s.streak,0);assert.equal(s.streakResult,null)});
test('full combats for each composition at all 25 stages terminate with valid state',()=>{for(const keys of Object.values(sets)){for(let round=1;round<=25;round++){const {g,s,field}=setup();field(keys);s.round=round;s.board.forEach(u=>{if(u)u.stage=1});g.startBattle();let ticks=0;while(s.battle&&ticks++<430){g.combatTick();if(s.combat)for(const c of s.combat.units){assert(Number.isFinite(c.hp));assert(Number.isFinite(c.speed));assert(c.hp>=0&&c.hp<=c.maxHp);assert(c.x>=0&&c.x<7&&c.y>=0&&c.y<6)}}assert(!s.battle);assert.equal(s.combat,null);assert(Number.isFinite(s.gold));assert(s.round===round+1||s.gameOver)}}});

test('items: all 15 unordered pairs preview and combine only after confirmation',()=>{const {g,s}=setup();assert.equal(g.COMPONENTS.length,5);assert.equal(Object.keys(g.ITEM_RECIPES).length,15);for(let i=0;i<5;i++)for(let j=i;j<5;j++){s.inventory=[g.newItem(g.COMPONENTS[i]),g.newItem(g.COMPONENTS[j])];const ids=s.inventory.map(x=>x.id);g.selectItem(ids[0]);g.selectItem(ids[1]);const plan=g.combinationPlan();assert(plan);assert.equal(s.inventory.length,2);assert.equal(plan.target,null);g.confirmCombine();assert.equal(s.inventory.length,1);assert.equal(s.inventory[0].key,plan.key);assert.equal(s.pendingCombine,null);g.confirmCombine();assert.equal(s.inventory.length,1)}});
test('items: cancel is lossless; mixed locations combine into holder, duplicate result goes to bag',()=>{const {g,s}=setup();const u=g.unit('pichu');s.bench[0]=u;u.items=[g.newItem('claw')];s.inventory=[g.newItem('claw')];g.selectItem(u.items[0].id);g.selectItem(s.inventory[0].id);g.cancelCombine();assert.equal(u.items.length,1);assert.equal(s.inventory.length,1);g.selectItem(u.items[0].id);g.selectItem(s.inventory[0].id);g.confirmCombine();assert.equal(u.items[0].key,'muscle');assert.equal(s.inventory.length,0);u.items.push(g.newItem('claw'));s.inventory.push(g.newItem('claw'));g.selectItem(u.items[1].id);g.selectItem(s.inventory[0].id);assert.equal(g.combinationPlan().target,null);g.confirmCombine();assert.equal(u.items.length,1);assert.equal(s.inventory[0].key,'muscle')});
test('items: three slots, duplicate equipment blocked, removal free',()=>{const {g,s}=setup();const u=g.unit('pichu');s.bench[0]=u;s.selected={id:u.id};s.inventory=['muscle','muscle','feather','crystal','seed'].map(g.newItem);const gold=s.gold;let ids=s.inventory.map(i=>i.id);for(const id of ids){s.selectedItem=id;g.equipSelectedItem()}assert.equal(u.items.length,3);assert.equal(u.items.filter(i=>i.key==='muscle').length,1);assert.equal(s.inventory.length,2);const item=u.items[0];g.removeItem(item.id);assert.equal(u.items.length,2);assert(s.inventory.includes(item));assert.equal(s.gold,gold)});
test('items: actions forbidden during combat/game-over; stale confirmations cannot duplicate',()=>{const {g,s}=setup();const u=g.unit('pichu');s.bench[0]=u;s.selected={id:u.id};s.inventory=[g.newItem('claw'),g.newItem('claw')];g.selectItem(s.inventory[0].id);g.selectItem(s.inventory[1].id);for(const mode of ['battle','gameOver']){s[mode]=true;g.confirmCombine();g.equipSelectedItem();assert.equal(s.inventory.length,2);assert.equal(u.items.length,0);s[mode]=false}s.inventory.pop();g.confirmCombine();assert.equal(s.inventory.length,1)});
test('items: evolution conserves nine items and returns duplicates/excess without auto-combining',()=>{const {g,s}=setup();s.inventory=[];const trio=[g.unit('mareep'),g.unit('mareep'),g.unit('mareep')];trio[0].items=['muscle','claw','seed'].map(g.newItem);trio[1].items=['muscle','scarf','feather'].map(g.newItem);trio[2].items=['bell','seed','shell'].map(g.newItem);const ids=trio.flatMap(u=>u.items.map(i=>i.id)).sort();s.board[21]=trio[0];s.bench[0]=trio[1];s.bench[1]=trio[2];g.tryMerge('mareep',0);const evolved=s.board[21];assert.equal(evolved.stage,1);assert.equal(evolved.items.length,3);assert.equal(new Set(evolved.items.map(i=>i.key)).size,3);assert.equal(s.inventory.length,6);assert.deepEqual([...evolved.items,...s.inventory].map(i=>i.id).sort(),ids)});
test('items: cascade evolution and sale return every item, without gold value from items',()=>{const {g,s}=setup();s.inventory=[];s.gold=100;const a=g.unit('mareep',1),b=g.unit('mareep',1),c=g.unit('mareep'),d=g.unit('mareep');a.items=[g.newItem('muscle')];b.items=[g.newItem('muscle'),g.newItem('bell')];c.items=[g.newItem('seed')];d.items=[g.newItem('shell')];const ids=[a,b,c,d].flatMap(u=>u.items.map(i=>i.id)).sort();s.board[21]=a;s.bench[0]=b;s.bench[1]=c;s.bench[2]=d;s.shop=['mareep'];g.buy(0);assert.equal(s.board[21].stage,2);s.selected={id:s.board[21].id};g.sellSelected();assert.deepEqual(Array.from(s.inventory,i=>i.id).sort(),ids);assert.equal(s.gold,116);assert.equal(s.board[21],null)});
test('items: preparation click flow selects, equips, previews, confirms and removes',()=>{const {g,s,nodes}=setup();const u=g.unit('pichu');s.bench[0]=u;s.selected={id:u.id};s.inventory=[g.newItem('claw'),g.newItem('claw')];g.render();nodes.get('#itemInventory').children[0].onclick();nodes.get('#equipItemBtn').onclick();assert.equal(u.items.length,1);nodes.get('#equipmentSlots').children[0].children[0].onclick();nodes.get('#itemInventory').children[0].onclick();const preview=nodes.get('#itemPreview').children[0];assert(preview.innerHTML.includes('Faixa Muscular'));preview.children[0].onclick();assert.equal(u.items[0].key,'muscle');nodes.get('#equipmentSlots').children[0].children[1].onclick();assert.equal(u.items.length,0);assert.equal(s.inventory[0].key,'muscle')});
test('v0.5: only two starting components are automatic; old round packages are removed',()=>{const {g,s}=setup();assert.equal(s.inventory.length,2);assert.deepEqual(Array.from(s.rewardRounds),[1]);for(const r of [4,7,10,13]){s.round=r;g.prepareItemRewards();assert.equal(s.inventory.length,2);assert.equal(s.rewardChoices,null)}assert.equal(s.gold,10)});
test('v0.5: boss schedule and exact boss rosters',()=>{const {g,s,field}=setup();assert.deepEqual(Array.from(g.BOSS_ROUNDS),[6,12,18,25]);assert.equal(s.maxRounds,25);for(const [round,key,count,dex] of [[6,'onix',1,95],[12,'tauros',3,128],[18,'suicune',1,245],[25,'mewtwo',1,150]]){s.round=round;if(round===18)s.legendaryBoss='suicune';field(['pichu']);g.startBattle();assert.equal(s.combat.bossKey,key);const enemies=s.combat.units.filter(c=>c.side==='enemy'&&!c.summoned);assert.equal(enemies.length,count);assert(enemies.every(c=>c.dex===dex&&c.boss));clearInterval(s.combat.timer);s.battle=false;s.combat=null}assert.equal(g.bossKeyForRound(18,'raikou'),'raikou');assert.equal(g.bossKeyForRound(18,'entei'),'entei');assert.equal(g.bossKeyForRound(18,'suicune'),'suicune')});
test('v0.5: boss reward gives 0 below half, 1 at half, and 2 on victory',()=>{for(const [win,ratio,expected] of [[false,.49,0],[false,.5,1],[false,.9,1],[true,1,2]]){const {g,s}=setup();s.round=6;s.inventory=[];s.bossRewards=[];const got=g.grantBossReward('onix',win,ratio);assert.equal(got,expected);assert.equal(s.inventory.length,expected);assert.equal(s.bossRewards.length,1);assert.equal(s.bossRewards[0].count,expected)}});
test('v0.5: first three stages are easy and later enemy teams activate traits',()=>{const {g,s}=setup();const p1=g.difficultyProfile(1),p2=g.difficultyProfile(2),p3=g.difficultyProfile(3),p17=g.difficultyProfile(17),p24=g.difficultyProfile(24);assert.deepEqual([p1.count,p2.count,p3.count],[1,1,2]);assert(p1.scale<p2.scale&&p2.scale<p3.scale);assert.equal(p1.synergy,0);assert.equal(p3.synergy,0);assert.equal(p17.synergy,5);assert.equal(p24.synergy,5);assert.equal(p24.count,7);s.round=17;const enemy=g.generateEnemy(),counts=g.countTypes(enemy);assert(Object.values(counts).some(n=>n>=5))});
test('items: reset clears equipment, selections and old rewards and grants only starting pair',()=>{const {g,s}=setup();const u=g.unit('pichu');u.items=[g.newItem('muscle')];s.bench[0]=u;s.round=4;g.prepareItemRewards();s.selectedItem=s.inventory[0].id;g.reset();assert.equal(s.inventory.length,2);assert.equal(s.bench.filter(Boolean).length,0);assert.equal(s.selectedItem,null);assert.equal(s.pendingCombine,null);assert.equal(s.rewardChoices,null);assert.equal(s.rewardRounds.length,1)});
function equipped({g},line,keys,tiers={}){const u=g.unit(line);u.items=keys.map(g.newItem);const c=g.makeCombatant(u,'player',0,3);g.applyBonus(c,tiers);return c}
test('items: exact stat totals replace components and stack additively across items, with traits afterward',()=>{const ctx=setup(),{g}=ctx;for(const [key,stat,factor] of [['muscle','atk',1.25],['scarf','speed',1.25],['glasses','power',1.25],['metal','def',1.35],['vest','maxHp',1.25]]){const c=equipped(ctx,'squirtle',[key]);const base=g.stageData(g.unit('squirtle'));if(stat==='power')assert.equal(c.bonus.power,factor);else if(stat==='speed')assert.equal(c.speed,base.speed*factor);else assert.equal(c[stat],Math.round((stat==='maxHp'?base.hp:base[stat])*factor))}const c=equipped(ctx,'charmander',['muscle','orb'],{Fire:2});assert.equal(c.atk,Math.round(22*1.45*1.3));assert.equal(c.bonus.power,1.2);const holder=equipped(ctx,'squirtle',['vest','barrier'],{Water:2});assert.equal(holder.maxHp,Math.round(118*1.25*1.35));assert.equal(holder.shield,Math.round(holder.maxHp*.2));const psychic=equipped(ctx,'abra',['glasses'],{Psychic:2});assert.equal(psychic.bonus.power,1.5)});
test('items: mana per attack caps at 100; Restos regen stacks with Water and respects poison healing reduction',()=>{const ctx=setup(),{g,fighter}=ctx;const a=equipped(ctx,'pichu',['amulet']),t=fighter('squirtle','enemy');t.hp=t.maxHp=1000;g.normalAttack(a,t);assert.equal(a.mana,44);a.mana=95;g.normalAttack(a,t);assert.equal(a.mana,100);const tank=equipped(ctx,'squirtle',['leftovers'],{Water:2});tank.hp=10;g.processEffects(tank,2999);assert.equal(tank.hp,10);g.processEffects(tank,3000);assert.equal(tank.hp,10+Math.round(tank.maxHp*.04));g.applyDot(tank,'poison',0,.3);const before=tank.hp;g.heal(tank,100);assert.equal(tank.hp,before+70)});
test('items: leech excludes shields, overkill, periodic damage and the other attack category',()=>{const ctx=setup(),{g,fighter}=ctx;const a=equipped(ctx,'charmander',['fang']),t=fighter('squirtle','enemy');a.hp=10;t.def=0;t.maxHp=t.hp=1000;t.shield=80;g.damage(a,t,100,'basic');assert.equal(a.hp,13);t.shield=100;g.damage(a,t,50,'basic');assert.equal(a.hp,13);t.shield=0;g.damage(a,t,100,'ability');assert.equal(a.hp,13);g.applyDot(t,'burn',.02);g.processEffects(t,3000);assert.equal(a.hp,13);t.hp=10;g.damage(a,t,100,'basic');assert.equal(a.hp,15);const caster=equipped(ctx,'abra',['bell']),e=fighter('squirtle','enemy');caster.hp=10;e.def=0;e.hp=e.maxHp=1000;g.damage(caster,e,100,'basic');assert.equal(caster.hp,10);g.damage(caster,e,100,'ability');assert.equal(caster.hp,25);caster.effects.poison={antiHeal:.3};g.damage(caster,e,100,'ability');assert.equal(caster.hp,36)});
test('items: ability power applies to damage, cure and shield, not just attacks',()=>{const ctx=setup(),{g,fighter}=ctx;for(const kind of ['blast','heal','shield']){const c=equipped(ctx,'squirtle',['glasses']),t=fighter('pichu','enemy'),ally=fighter('pichu');t.def=0;t.hp=t.maxHp=1000;ally.hp=1;ally.maxHp=1000;c.ability={kind,power:.5};g.cast(c,[t],[c,ally]);if(kind==='blast')assert.equal(1000-t.hp,Math.round(c.atk*.5*1.25));if(kind==='heal')assert.equal(ally.hp,1+Math.round(c.maxHp*.5*1.25));if(kind==='shield')assert.equal(c.shield,Math.round(c.maxHp*.5*1.25))}});
test('items: battle copies do not mutate original stats or inventory; Zapdos cannot receive items',()=>{const {g,s,field}=setup();field(sets.Electric);s.board[21].items=[g.newItem('vest'),g.newItem('muscle')];const owned=JSON.stringify(s.board);g.startBattle();const first=s.combat.units.find(c=>c.side==='player'&&!c.summoned),hp=first.maxHp;const z=s.combat.units.find(c=>c.summoned&&c.side==='player');assert.equal(z.maxHp,180);const item=g.newItem('vest');s.inventory.push(item);s.selected={id:z.cid};s.selectedItem=item.id;g.equipSelectedItem();assert(s.inventory.includes(item));g.finishBattle(true);assert.equal(JSON.stringify(s.board),owned);g.startBattle();assert.equal(s.combat.units.find(c=>c.side==='player'&&!c.summoned).maxHp,hp)});
test('items: entire 25-stage journey with bosses keeps equipment and terminates',()=>{const {g,s,field}=setup();field(sets.Water);s.hp=10000;s.board[21].items=['leftovers','vest','barrier'].map(g.newItem);s.board[22].items=['orb','bell','amulet'].map(g.newItem);const before=JSON.stringify(s.board);for(let round=1;round<=25;round++){assert.equal(s.rewardChoices,null);assert.equal(s.round,round);g.startBattle();let ticks=0;while(s.battle&&ticks++<430)g.combatTick();assert.equal(s.battle,false);assert.equal(JSON.stringify(s.board),before)}assert(s.gameOver);assert(s.inventory.length>=2&&s.inventory.length<=10);assert.equal(s.rewardRounds.length,1);assert.equal(s.bossRewards.length,4)});

test('v0.5: three Tauros use a combined HP pool for the 50% reward threshold',()=>{const {g,s,field}=setup();field(['pichu']);s.round=12;g.startBattle();assert.equal(s.combat.bossInitialHp,g.BOSS_DEFS.tauros.hp*3);const bosses=s.combat.units.filter(c=>c.boss);bosses[0].hp=0;bosses[0].dead=true;bosses[1].hp=g.BOSS_DEFS.tauros.hp*.5;bosses[2].hp=g.BOSS_DEFS.tauros.hp;const before=s.inventory.length;g.finishBattle(false);assert.equal(s.bossRewards.at(-1).count,1);assert.equal(s.inventory.length,before+1)});

test('v0.6 shop odds are exact from level 2 through 9 and unlock 4-star only at level 6',()=>{const {g}=setup();const expected={2:[70,30,0,0],3:[55,35,10,0],4:[40,35,25,0],5:[28,37,35,0],6:[18,32,47,3],7:[10,25,57,8],8:[5,18,65,12],9:[3,12,67,18]};for(const [level,odds] of Object.entries(expected)){const got=Array.from(g.shopOdds(Number(level)));assert.deepEqual(got,odds);assert.equal(got.reduce((a,b)=>a+b,0),100)}});
test('v0.6 evolution odds are exact for normal and special offers',()=>{const {g}=setup();assert.deepEqual(Array.from(g.stageOdds(2,false)),[100,0,0]);assert.deepEqual(Array.from(g.stageOdds(6,false)),[70,25,5]);assert.deepEqual(Array.from(g.stageOdds(9,false)),[40,37,23]);assert.deepEqual(Array.from(g.stageOdds(6,true)),[94,5,1]);assert.deepEqual(Array.from(g.stageOdds(9,true)),[62,26,12])});
test('v0.6 evolved offer prices and four-star prices are preserved',()=>{const {g}=setup();assert.equal(g.unitPrice('charmander',0),2);assert.equal(g.unitPrice('charmander',1),6);assert.equal(g.unitPrice('charmander',2),18);assert.equal(g.unitPrice('dratini',0),4);assert.equal(g.unitPrice('dratini',1),9);assert.equal(g.unitPrice('dratini',2),16);assert.equal(g.unitPrice('gible',0),4)});
test('v0.6 shop can buy a directly evolved unit and merge from that stage',()=>{const {g,s}=setup();s.gold=100;s.shop=[{line:'charmander',stage:1}];g.buy(0);assert.equal(s.gold,94);assert.equal(s.bench[0].line,'charmander');assert.equal(s.bench[0].stage,1);s.bench[1]=g.unit('charmander',1);s.shop=[{line:'charmander',stage:1}];g.buy(0);assert.equal(s.bench.filter(Boolean).length,1);assert.equal(s.bench.find(Boolean).stage,2)});
test('v0.6 normal enemy generator never pulls player-only special 4-star lines',()=>{const {g,s}=setup();for(let round=1;round<=25;round++){if(g.BOSS_ROUNDS.includes(round))continue;s.round=round;for(let n=0;n<25;n++){const enemy=g.generateEnemy();assert(enemy.every(c=>!g.SPECIAL_KEYS.includes(c.line)))}}});
test('v0.7 special passives scale by evolution stage',()=>{const {g}=setup();for(const [line,key,vals] of [['dratini','values',[.15,.25,.35]],['larvitar','slow',[.08,.12,.18]],['gastly','intangibility',[400,700,1000]],['gible','reflect',[.08,.12,.18]],['beldum','guard',[.5,.75,1]]])for(let stage=0;stage<3;stage++){const p=g.stageData(g.unit(line,stage));assert.equal(p.special,true);assert.equal(p.passive[key],vals[stage])}});
test('v0.6 Multiscale reduces damage above 70 percent and stops below threshold',()=>{const {g,s}=setup();const d=g.makeCombatant(g.unit('dratini',2),'player',0,3),a=g.makeCombatant(g.unit('pichu'),'enemy',0,2);g.applyBonus(d,{});g.applyBonus(a,{});s.combat={units:[d,a],elapsedMs:0};g.applySpecialBattleStart('player');d.def=0;const hp=d.hp;g.damage(a,d,100,'ability');assert.equal(hp-d.hp,65);d.hp=d.maxHp*.7;const before=d.hp;g.damage(a,d,100,'ability');assert.equal(before-d.hp,100)});
test('v0.6 sandstorm scales slow and self defense without stacking duplicate storms',()=>{const {g,s}=setup();const tyr=g.makeCombatant(g.unit('larvitar',2),'player',0,3),foe=g.makeCombatant(g.unit('pichu'),'enemy',0,2);g.applyBonus(tyr,{});g.applyBonus(foe,{});const baseDef=tyr.def;s.combat={units:[tyr,foe],elapsedMs:0};g.applySpecialBattleStart('player');assert.equal(foe.sandSlow,.18);assert.equal(tyr.def,Math.round(baseDef*1.30))});
test('v0.6 Gastly line starts intangible for stage-scaled duration',()=>{const {g,s}=setup();const h=g.makeCombatant(g.unit('gastly',1),'player',0,3),a=g.makeCombatant(g.unit('pichu'),'enemy',0,2);g.applyBonus(h,{});g.applyBonus(a,{});s.combat={units:[h,a],elapsedMs:0};g.applySpecialBattleStart('player');assert.equal(h.intangibleUntil,700);const hp=h.hp;g.damage(a,h,100,'ability');assert.equal(h.hp,hp);s.combat.elapsedMs=700;g.damage(a,h,100,'ability');assert(h.hp<hp)});
test('v0.7 Gible line reflects a growing share of basic-attack damage with Rough Skin',()=>{const {g,s}=setup();for(const [stage,rate] of [[0,.08],[1,.12],[2,.18]]){const target=g.makeCombatant(g.unit('gible',stage),'player',0,3),att=g.makeCombatant(g.unit('pichu'),'enemy',0,2);g.applyBonus(target,{});g.applyBonus(att,{});target.def=0;att.def=0;s.combat={units:[target,att],elapsedMs:0};g.applySpecialBattleStart('player');const before=att.hp;g.damage(att,target,100,'basic');assert.equal(before-att.hp,Math.round(100*rate))}});
test('v0.6 Metal Body progressively reduces the first control and Metagross ignores it',()=>{const {g,s}=setup();for(const [stage,expected] of [[0,1],[1,1],[2,0]]){const m=g.makeCombatant(g.unit('beldum',stage),'player',0,3),foe=g.makeCombatant(g.unit('zubat'),'enemy',0,2);g.applyBonus(m,{});g.applyBonus(foe,{});s.combat={units:[m,foe],elapsedMs:0};g.applySpecialBattleStart('player');g.applyStun(m,2);assert.equal(m.stun,expected);assert.equal(m.controlGuardUsed,true);g.applyStun(m,2);assert.equal(m.stun,2)}});

test('v0.7 special active abilities exist from the first form and scale through evolution',()=>{const {g}=setup();for(const line of ['dratini','larvitar','gastly','gible','beldum']){const first=g.stageData(g.unit(line,0)),final=g.stageData(g.unit(line,2));assert(first.ability);assert(final.ability);assert(final.ability.power>first.ability.power)}});
test('v0.7 special active abilities execute their effects',()=>{const {g,s}=setup();
  const foe=line=>{const c=g.makeCombatant(g.unit(line),'enemy',3,1);g.applyBonus(c,{});c.def=0;c.hp=c.maxHp=1000;return c};
  {const c=g.makeCombatant(g.unit('dratini'),'player',0,3),e=foe('squirtle');g.applyBonus(c,{});s.combat={units:[c,e],elapsedMs:0};g.cast(c,[e],[c]);assert.equal(c.speedBoost,.15);assert.equal(c.speedBoostUntil,2200)}
  {const c=g.makeCombatant(g.unit('larvitar'),'player',3,3),e=foe('squirtle');e.x=3;e.y=2;g.applyBonus(c,{});s.combat={units:[c,e],elapsedMs:0};g.cast(c,[e],[c]);assert.equal(e.stun,1);assert(e.hp<1000)}
  {const c=g.makeCombatant(g.unit('gastly'),'player',0,3),e=foe('squirtle');g.applyBonus(c,{});e.hp=1;s.combat={units:[c,e],elapsedMs:0};g.cast(c,[e],[c]);assert.equal(e.dead,true);assert.equal(c.mana,20)}
  {const c=g.makeCombatant(g.unit('gible'),'player',0,3),e=foe('squirtle');g.applyBonus(c,{});s.combat={units:[c,e],elapsedMs:0};g.cast(c,[e],[c]);assert.equal(c.speedBoost,.10);assert.equal(c.speedBoostUntil,1800);assert(e.hp<1000)}
  {const c=g.makeCombatant(g.unit('beldum'),'player',0,3),e=foe('squirtle');g.applyBonus(c,{});s.combat={units:[c,e],elapsedMs:0};g.cast(c,[e],[c]);assert.equal(c.shield,Math.round(c.maxHp*.05))}
});
test('v0.6 gameplay shop stays compact while complete odds remain in the info panel',()=>{const {g,s,nodes}=setup();s.level=6;g.render();const t=nodes.get('#shopOddsText').textContent;assert.equal(t,'Nv. 6 • 4★ 3%');assert(!t.includes('base'));g.renderShopInfo();const h=nodes.get('#shopInfoContent').innerHTML;assert(h.includes('70 / 25 / 5%'));s.level=9;g.render();assert.equal(nodes.get('#shopOddsText').textContent,'Nv. 9 • 4★ 18%');assert(h.includes('B/2ª/F'))});

test('v0.7 type encyclopedia follows current evolutionary typings',()=>{const {g}=setup();const flying=Array.from(g.typeCatalog('Flying'),x=>x.name);assert(flying.includes('Crobat'));assert(flying.includes('Butterfree'));assert(flying.includes('Charizard'));assert(!flying.includes('Charmander'));assert(!flying.includes('Charmeleon'));assert(flying.includes('Dragonite'));const poison=Array.from(g.typeCatalog('Poison'),x=>x.name);assert(poison.includes('Dustox'));assert(poison.includes('Gastly'));const water=Array.from(g.typeCatalog('Water'),x=>x.name);assert(water.includes('Horsea'));assert(water.includes('Kingdra'));assert(water.includes('Lotad'));const ground=Array.from(g.typeCatalog('Ground'),x=>x.name);assert(ground.includes('Rhyhorn'));assert(ground.includes('Marshtomp'));assert(ground.includes('Garchomp'));const dragon=Array.from(g.typeCatalog('Dragon'),x=>x.name);assert(dragon.includes('Dratini'));assert(dragon.includes('Gible'));assert(dragon.includes('Vibrava'));assert(dragon.includes('Flygon'));assert(dragon.includes('Kingdra'));assert(!dragon.includes('Trapinch'));assert(!dragon.includes('Horsea'));assert(!dragon.includes('Seadra'))});
test('v0.7 type modal renders each synergy own thresholds including Dragon 1/4',()=>{const {g,nodes}=setup();g.openTypeInfo('Fire');assert.equal(nodes.get('#typeModal').dataset.type,'Fire');assert(nodes.get('#typeModalEffects').innerHTML.includes('3 linhas diferentes'));assert(nodes.get('#typeModalEffects').innerHTML.includes('5 linhas diferentes'));assert(nodes.get('#typeModalCatalog').innerHTML.includes('Charmander'));assert(nodes.get('#typeModalCatalog').innerHTML.includes('Charizard'));g.closeTypeInfo();g.openTypeInfo('Dragon');const h=nodes.get('#typeModalEffects').innerHTML;assert(h.includes('1 linha diferente'));assert(h.includes('4 linhas diferentes'));assert(h.includes('Ascensão Dracônica'));assert(nodes.get('#typeModalCatalog').innerHTML.includes('Garchomp'));assert(nodes.get('#typeModalCatalog').innerHTML.includes('Kingdra'));g.closeTypeInfo();assert.equal(nodes.get('#typeModal').dataset.type,'')});
test('v0.6 synergy entries are interactive buttons that open the encyclopedia',()=>{const {g,nodes}=setup();g.renderSynergies();const first=nodes.get('#synergies').children[0];assert.equal(first.type,'button');assert.equal(typeof first.onclick,'function');first.onclick();assert(nodes.get('#typeModal').dataset.type)});
test('v0.6 selected Pokemon panel exposes rarity, stage, ability explanation, passive and equipment',()=>{const {g,s,nodes}=setup();const u=g.unit('dratini',1);u.items=[g.newItem('claw')];s.bench[0]=u;s.selected={id:u.id};g.render();const html=nodes.get('#selectedBox').innerHTML;assert(html.includes('★★★★'));assert(html.includes('Evolução 2'));assert(html.includes('Fúria do Dragão'));assert(html.includes('Multiescala'));assert(html.includes('Garra'))});
test('v0.6 shop lock preserves offers between rounds but manual reroll still refreshes',()=>{const {g,s}=setup();s.gold=100;const before=JSON.stringify(s.shop);g.toggleShopLock();assert.equal(s.shopLocked,true);g.rollShop(true);assert.equal(JSON.stringify(s.shop),before);g.rollShop(false);assert.notEqual(JSON.stringify(s.shop),before);assert.equal(s.shopLocked,true);g.toggleShopLock();assert.equal(s.shopLocked,false)});
test('v0.6 battle preview stays compact and keeps boss reward rules in the tooltip',()=>{const {g,s,nodes}=setup();s.round=5;g.renderBattlePreview();assert(nodes.get('#nextBattlePreview').innerHTML.includes('Etapa 5'));s.round=12;g.renderBattlePreview();const node=nodes.get('#nextBattlePreview');assert(node.innerHTML.includes('3× Tauros'));assert(!node.innerHTML.includes('2 componentes'));assert(node.title.includes('2 componentes'));assert(node.title.includes('50%'))});
test('v0.6 shop information panel contains all levels 2 through 9 and evolution odds',()=>{const {g,nodes}=setup();g.openShopInfo();const h=nodes.get('#shopInfoContent').innerHTML;for(let l=2;l<=9;l++)assert(h.includes('Nv '+l));assert(h.includes('4★'));assert(h.includes('B/2ª/F'));g.closeShopInfo()});
test('v0.6 post-battle summary stores result, damage, income and boss percentage',()=>{const {g,s,field,nodes}=setup();field(['pichu']);s.round=6;g.startBattle();const boss=s.combat.units.find(c=>c.boss);boss.hp=boss.maxHp*.4;g.finishBattle(false);assert.equal(s.lastBattleSummary.round,6);assert.equal(s.lastBattleSummary.win,false);assert.equal(s.lastBattleSummary.bossDamagePct,60);assert.equal(s.lastBattleSummary.bossReward,1);g.renderBattleSummary();assert(nodes.get('#battleSummary').innerHTML.includes('60%'))});
test('v0.7 final summary contains stage, record, bosses, final team and four-star history',()=>{const {g,s,nodes}=setup();s.board[21]=g.unit('gible');s.runStats.wins=12;s.runStats.losses=3;s.runStats.specialSeen=['gible','dratini'];s.runStats.specialBought=['gible'];s.round=25;s.bossRewards=[{count:2},{count:1},{count:2},{count:0}];g.showFinalSummary();const h=nodes.get('#finalContent').innerHTML;assert(h.includes('25/25'));assert(h.includes('12 / 3'));assert(h.includes('2/4'));assert(h.includes('Gible'));assert(h.includes('Dratini'));g.closeFinalSummary()});
test('v0.6 level 9 progression remains reachable without changing XP or economy rules',()=>{const {g,s}=setup();let passiveXp=25*2,totalNeeded=0;for(let l=2;l<9;l++)totalNeeded+=l*4;assert.equal(totalNeeded,140);assert.equal(passiveXp,50);assert.equal(Math.ceil((totalNeeded-passiveXp)/4),23);assert.equal(23*4,92);s.gold=1000;for(let i=0;i<35;i++)g.buyXP();assert.equal(s.level,9)});
test('v0.6 boss and four-star balance sanity keeps approved stats finite and escalating identities',()=>{const {g}=setup();for(const b of Object.values(g.BOSS_DEFS)){assert(b.hp>0&&b.atk>0&&b.def>=0&&b.speed>0)}for(const k of g.SPECIAL_KEYS){const l=g.LINES[k];for(let st=0;st<l.stages.length;st++){const p=g.stageData(g.unit(k,st));assert(p.hp>0&&p.atk>0&&p.def>=0&&p.speed>0)}if(l.stages.length===3){assert(g.stageData(g.unit(k,2)).atk>g.stageData(g.unit(k,0)).atk)}}});
test('v0.6 start screen teaches the core loop and game begins without resetting mechanics',()=>{const {g,s,nodes}=setup();const gold=s.gold,shop=JSON.stringify(s.shop);assert(html.includes('id="startScreen"'));assert(html.includes('id="gameApp"'));g.startGame();assert.equal(nodes.get('#startScreen').style.display,'none');assert.equal(s.gold,gold);assert.equal(JSON.stringify(s.shop),shop)});
test('v0.6 rules, backpack and history are modal utilities instead of permanent gameplay text',()=>{const {g,nodes}=setup();g.openRules();assert(nodes.get('#rulesModal').classList.contains('open'));g.closeRules();assert(!nodes.get('#rulesModal').classList.contains('open'));g.openBackpack();assert(nodes.get('#backpackModal').classList.contains('open'));assert(nodes.get('#itemInventory'));g.closeBackpack();g.openHistory();assert(nodes.get('#historyModal').classList.contains('open'));assert(nodes.get('#log'));g.closeHistory()});
test('v0.6 future visual slots exist for logo, hero art and background variables',()=>{assert(html.includes('data-art-slot="logo"'));assert(html.includes('data-art-slot="hero"'));assert(html.includes('--game-bg-image:none'));assert(html.includes('--start-bg-image:none'));assert(html.includes('--logo-image:none'));assert(html.includes('--hero-image:none'))});
test('v0.6 gameplay screen no longer contains permanent quick-rules or inline backpack sections',()=>{assert(!html.includes('<h2 style="margin-top:10px">Regras rápidas</h2>'));assert(!html.includes('<section class="panel items-panel"'));assert(html.includes('id="backpackModal"'));assert(html.includes('id="historyModal"'))});
test('interest: balance brackets before payout, both results, cap and streak resets',()=>{
  for(const win of [true,false])for(const gold of [0,9,10,19,20,29,30,35,39,40,49,50,59,100]){
    const {g,s}=setup();s.gold=gold;s.streak=2;s.streakResult=win?'win':'loss';s.combat={units:[]};
    g.finishBattle(win);assert.equal(s.gold,gold+(win?6:5)+Math.min(5,Math.floor(gold/10))+1);
  }
  const {g,s}=setup();s.gold=40;s.gold-=5;s.streak=5;s.streakResult='win';s.combat={units:[]};
  g.finishBattle(false);assert.equal(s.gold,43);assert.equal(s.streak,1);assert.equal(s.streakResult,'loss');
  s.gold=40;s.streak=5;s.streakResult='loss';s.combat={units:[]};
  g.finishBattle(true);assert.equal(s.gold,50);assert.equal(s.streak,1);assert.equal(s.streakResult,'win');
});
test('visible XP: initial, purchase, round reward, level rollover, maximum and reset',()=>{
  const {g,s,nodes}=setup();const text=()=>nodes.get('#xpStat').textContent;
  assert.equal(text(),'0/8 XP');s.gold=100;g.buyXP();assert.equal(text(),'4/8 XP');assert.equal(nodes.get('#xpFill').style.width,'50%');
  s.combat={units:[]};g.finishBattle(false);assert.equal(text(),'6/8 XP');
  g.buyXP();assert.equal(s.level,3);assert.equal(text(),'2/12 XP');assert.equal(nodes.get('#xpProgress')['aria-valuenow'],'2');
  s.level=8;s.xp=31;g.render();assert.equal(text(),'31/32 XP');s.gold=100;g.buyXP();assert.equal(s.level,9);assert.equal(text(),'XP • Nível máximo');assert.equal(nodes.get('#xpFill').style.width,'100%');
  g.reset();assert.equal(text(),'0/8 XP');assert.equal(nodes.get('#xpFill').style.width,'0%');
});