#!/usr/bin/env bash
set -euo pipefail
python3 - <<'PY'
from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')
marker='/* ===== TFTMON EXACT APPROVED FLOATING ARENA — 2026-10-05 ===== */'
start=s.find(marker)
if start<0: raise SystemExit('arena marker not found')
end=s.find('</style>',start)
if end<0: raise SystemExit('style end not found')
rows=[
 (26.0,79.0,11.5,21.5),
 (24.8,80.2,21.5,31.8),
 (23.6,81.4,31.8,42.3),
 (22.7,82.3,45.5,57.2),
 (21.5,83.5,57.2,69.2),
 (20.3,84.7,69.2,81.5),
]
css='''/* ===== TFTMON EXACT APPROVED FLOATING ARENA — 2026-10-05 ===== */
/* The decorative artwork is only the frame. The visible 7x6 board below is
   generated by CSS, so the visual tiles and the actual drop targets are identical. */
#gameApp .arena-decor{display:none!important}
#gameApp .board,
#gameApp .battle-preview[data-boss] + .board{
  position:relative!important;
  isolation:isolate!important;
  display:block!important;
  width:min(100%,1160px)!important;
  max-width:1160px!important;
  aspect-ratio:1160/340!important;
  height:auto!important;
  margin:4px auto 26px!important;
  padding:0!important;
  overflow:hidden!important;
  border:0!important;
  border-radius:0!important;
  background-color:#173d55!important;
  background-image:url('assets/tftmon-arena-approved.webp')!important;
  background-size:100% auto!important;
  background-position:center top!important;
  background-repeat:no-repeat!important;
  box-shadow:none!important;
}
/* Cover the old baked-in grid. The new grid is the real gameplay grid. */
#gameApp .board::before,
#gameApp .board::after{
  content:""!important;
  display:block!important;
  position:absolute!important;
  z-index:1!important;
  pointer-events:none!important;
  box-shadow:inset 0 0 28px rgba(0,0,0,.18)!important;
}
#gameApp .board::before{
  left:22.7%!important;right:17.5%!important;top:10.5%!important;height:33.2%!important;
  clip-path:polygon(5.5% 0,94.5% 0,100% 100%,0 100%)!important;
  background:linear-gradient(180deg,rgba(139,65,42,.98),rgba(113,50,36,.98))!important;
  border:1px solid rgba(243,123,74,.45)!important;
}
#gameApp .board::after{
  left:19.2%!important;right:14.2%!important;top:44.2%!important;height:39.0%!important;
  clip-path:polygon(4.5% 0,95.5% 0,100% 100%,0 100%)!important;
  background:linear-gradient(180deg,rgba(47,97,156,.99),rgba(36,78,137,.99))!important;
  border:1px solid rgba(73,161,255,.42)!important;
}
#gameApp .cell{
  position:absolute!important;
  min-width:0!important;min-height:0!important;
  z-index:2!important;
  overflow:visible!important;
  border:0!important;background:transparent!important;
  box-shadow:none!important;border-radius:6px!important;outline:none!important;
}
#gameApp .cell::before{
  content:""!important;display:block!important;position:absolute!important;inset:1px!important;
  z-index:0!important;border-radius:6px!important;
  background:rgba(255,255,255,.015)!important;
  box-shadow:inset 0 0 8px rgba(0,0,0,.18)!important;
  opacity:1!important;transition:.14s ease!important;
}
#gameApp .enemy-zone::before{border:1.5px solid rgba(240,120,69,.68)!important}
#gameApp .player-zone::before{border:1.5px solid rgba(68,156,255,.72)!important}
#gameApp .cell::after{display:none!important}
#gameApp .cell:hover::before{background:rgba(255,255,255,.09)!important;box-shadow:inset 0 0 12px rgba(255,255,255,.10),0 0 9px currentColor!important}
#gameApp .board.dragging-active .player-zone::before{border-color:#8cf3ff!important;background:rgba(39,217,255,.11)!important;box-shadow:inset 0 0 13px rgba(41,223,255,.18),0 0 9px rgba(41,221,255,.32)!important}
#gameApp .board.dragging-active .enemy-zone::before{opacity:.38!important}
#gameApp .cell.drag-over::before{border-color:#ffe36c!important;background:rgba(255,216,76,.15)!important;box-shadow:inset 0 0 15px rgba(255,216,76,.22),0 0 12px rgba(255,216,76,.48)!important}
#gameApp .battle-layer,#gameApp .fx-layer{inset:0!important;top:0!important;right:0!important;bottom:0!important;left:0!important;overflow:visible!important;pointer-events:none!important}
#gameApp .battle-layer{z-index:40!important} #gameApp .fx-layer{z-index:25!important}
#gameApp .fighter{width:8.5%!important;height:24%!important;transform-origin:center bottom!important;scale:var(--arena-depth,1);overflow:visible!important}
#gameApp .fighter-sprite,#gameApp .fighter-sprite img{overflow:visible!important}
'''
for r,(xl,xr,yt,yb) in enumerate(rows):
    width=(xr-xl)/7
    for c in range(7):
        i=r*7+c+1
        x=xl+width*c
        css+=f"#gameApp .cell:nth-child({i}){{left:{x:.4f}%!important;top:{yt:.4f}%!important;width:{width:.4f}%!important;height:{yb-yt:.4f}%!important}}\n"
css+='''
#gameApp .cell:nth-child(-n+7) .token{scale:.84;transform-origin:center bottom}
#gameApp .cell:nth-child(n+8):nth-child(-n+14) .token{scale:.88;transform-origin:center bottom}
#gameApp .cell:nth-child(n+15):nth-child(-n+21) .token{scale:.92;transform-origin:center bottom}
#gameApp .cell:nth-child(n+22):nth-child(-n+28) .token{scale:.96;transform-origin:center bottom}
#gameApp .cell:nth-child(n+29):nth-child(-n+35) .token{scale:1;transform-origin:center bottom}
#gameApp .cell:nth-child(n+36):nth-child(-n+42) .token{scale:1.04;transform-origin:center bottom}
@media(max-width:820px){
 #gameApp .board,#gameApp .battle-preview[data-boss] + .board{width:min(calc(100vw - 6px),1160px)!important;max-width:calc(100vw - 6px)!important;aspect-ratio:1160/340!important;margin:2px auto 22px!important}
 #gameApp .fighter{width:9%!important;height:25%!important}
 #gameApp .cell::before{inset:.5px!important;border-radius:4px!important}
}
'''
s=s[:start]+css+'\n'+s[end:]
old='''      const arenaTy=(c.y+.5)/6;
      const arenaLeftPct=23.8+(19.5-23.8)*arenaTy,arenaRightPct=79.2+(83.0-79.2)*arenaTy;
      const arenaXPct=arenaLeftPct+(arenaRightPct-arenaLeftPct)*((c.x+.5)/7);
      const arenaYPct=c.y<3?(12.7+c.y*10.0):(45.5+(c.y-3)*12.7);
      d.style.left=(layer.clientWidth*arenaXPct/100-layer.clientWidth*.0425)+'px';
      d.style.top=(layer.clientHeight*arenaYPct/100-layer.clientHeight*.12)+'px';
      d.style.setProperty('--arena-depth',(0.82+arenaTy*.26).toFixed(3));'''
new='''      const boardCell=cells[Math.max(0,Math.min(41,c.y*7+c.x))];
      if(boardCell){
        const lr=layer.getBoundingClientRect(),cr=boardCell.getBoundingClientRect();
        const cx=cr.left-lr.left+cr.width/2,cy=cr.top-lr.top+cr.height/2;
        d.style.left=(cx-layer.clientWidth*.0425)+'px';
        d.style.top=(cy-layer.clientHeight*.115)+'px';
        d.style.setProperty('--arena-depth',(0.84+(c.y/5)*.22).toFixed(3));
      }'''
if s.count(old)!=1: raise SystemExit(f'combat positioning block count={s.count(old)}')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
PY
git diff --check
git config user.name 'github-actions[bot]'
git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
git add index.html
git commit -m 'Align 7x6 arena grid and hide corrupted artwork strip'
git push origin HEAD:main
